version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: some-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: phpmyadmin
      MARIADB_DATABASE: phpmyadmin
      MARIADB_USER: phpmyadmin
      MARIADB_PASSWORD: phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: phpmyadmin
      PMA_PASSWORD: phpmyadmin
      PMA_ABSOLUTE_URI: http://localhost:8080/

volumes:
  db_data: {}
